In [1]:
# 1. What is a Python library? Why do we use Python libraries?

"""A Python library is a collection of pre-written code, functions, modules, and methods that extend the capabilities of Python.
These libraries provide reusable functions and classes that developers can use to perform specific tasks without having to write the code from scratch.
We use python for many resons :
1. Code reusability
2. Increase productivity
3. Specialized Functionality
4. Performance Optimization, etc"""

'A Python library is a collection of pre-written code, functions, modules, and methods that extend the capabilities of Python.\nThese libraries provide reusable functions and classes that developers can use to perform specific tasks without having to write the code from scratch.\nWe use python for many resons :\n1. Code reusability\n2. Increase productivity\n3. Specialized Functionality\n4. Performance Optimization, etc'

In [2]:
# 2. What is the difference between Numpy array and List?

"""NumPy arrays and Python lists are both used to store collections of data, but they have some key differences:
1. NumPy arrays are homogeneous, meaning that all elements in the array must have the same data type whereas Python lists can hold elements of different data types, making them more flexible but potentially less efficient for numerical computations.
2. Numpy store data in contiguous memory blocks and have a fixed size whereas List store references to objects, which can lead to more memory overhead and fragmentation.
3. umPy arrays are preferred for numerical computations and operations on large datasets due to their efficiency and performance, while Python lists are more versatile and suitable for general-purpose use cases.
"""

'NumPy arrays and Python lists are both used to store collections of data, but they have some key differences:\n1. NumPy arrays are homogeneous, meaning that all elements in the array must have the same data type whereas Python lists can hold elements of different data types, making them more flexible but potentially less efficient for numerical computations.\n2. Numpy store data in contiguous memory blocks and have a fixed size whereas List store references to objects, which can lead to more memory overhead and fragmentation.\n3. umPy arrays are preferred for numerical computations and operations on large datasets due to their efficiency and performance, while Python lists are more versatile and suitable for general-purpose use cases.\n'

In [3]:
# 3.  Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr_shape = arr.shape
arr_size = arr.size
arr_dim = arr.ndim
print("Shape of the given array is : ", arr_shape)
print("Size of the given array is : ", arr_size)
print("Dimension of the given array is : ", arr_dim)

Shape of the given array is :  (3, 4)
Size of the given array is :  12
Dimension of the given array is :  2


In [4]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
first_row = arr2[0]

print("First row of the array:", first_row)

First row of the array: [1 2 3 4]


In [5]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr3 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
element = arr3[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


In [6]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr4 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
odd_indexed_elements = arr4[:, 1::2]

print("Odd-indexed elements from the array: \n", odd_indexed_elements)


Odd-indexed elements from the array: 
 [[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 and 1?

arr5 = np.random.rand(3,3)
arr5

array([[0.42242794, 0.75175468, 0.88198492],
       [0.8254828 , 0.31266231, 0.83847333],
       [0.61454871, 0.83885442, 0.44064567]])

In [8]:
# 8. Describe the difference between np.random.rand and np.random.randn?

"""np.random.rand generates random numbers from a uniform distribution over the interval [0, 1), while np.random.randn generates random numbers from a standard normal distribution."""

'np.random.rand generates random numbers from a uniform distribution over the interval [0, 1), while np.random.randn generates random numbers from a standard normal distribution.'

In [9]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr6 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("Array after increasing dimension : \n", arr6.reshape(2,2,3))

Array after increasing dimension : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

arr7 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("Array after transpose is : \n", arr7.T)

Array after transpose is : 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [11]:
# 11.  Consi^er the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

# Perform the following operation using Python1

arr8 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr9 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# Index wise multiplication.
arr8*arr9

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [12]:
# Matrix Multiplication
# Not possible because requirement not matched for matrix multiplication but can be done with transpose

arr8 @ arr9.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [13]:
# Add both matrix
arr8 + arr9

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [14]:
# Subtract matrix B from matrix A
arr8 - arr9

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
# Divide matrix B by A
arr9/arr8

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# 12. Which function in Numpy can be used to swap the byte or^er of an array?

"""np.ndarray.byteswap()"""

'np.ndarray.byteswap()'

In [17]:
# 13.  What is the significance of the np.linalg.inv function?

"""The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix."""

'The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.'

In [18]:
# 14. What does the np.reshape function do, and how is it used?

"""The np.reshape function in NumPy is used to change the shape (dimensions) of an array while keeping the underlying data unchanged. It allows you to reorganize the elements of the array into a new shape without altering their values."""

arr10 = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr10, (2, 3))

print("Original array:")
print(arr10)

print("\nReshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [19]:
# 15. What is broadcasting in Numpy?

"""Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together in arithmetic operations, even if their shapes do not match exactly. It enables efficient computation on arrays without the need for explicit looping operations."""

'Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined together in arithmetic operations, even if their shapes do not match exactly. It enables efficient computation on arrays without the need for explicit looping operations.'